# Generated by Django 2.2.3 on 2019-07-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190715_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='client_firstname',
            field=models.CharField(default='Test Fname', max_length=50),
        ),
    ]
