using System;
using System.Collections.Generic;
using System.Text;

namespace FILogger.IdentityServer.Tests
{
    public static class Mocks
    {
        public static string MockIdentitySettingsJSON = "  { 'ApiResources': [ { 'name': 'TestAPI', 'displayName': 'Test API' } ], 'Clients': [ { 'clientId': 'Test_Client_1', 'clientName': 'Test_Client', 'allowAccessTokensViaBrowser': true, 'requireConsent': false, 'accessTokenLifetime': 3600, 'redirectUris': [ 'http://testhost1:', 'http://testhost2' ], 'postLogoutRedirectUris': [ 'http://testhost/account/login' ], 'allowedCorsOrigins': [ 'http://testhost' ], 'AllowedGrantTypes': [ 'implicit' ], 'allowedScopes': [ 'openid', 'profile', 'testAPI' ] }, { 'clientId': 'Test_Client_2', 'clientName': 'Test Client 2', 'allowAccessTokensViaBrowser': true, 'requireConsent': false, 'accessTokenLifetime': 43200, 'redirectUris': [ 'http://testSwaggerhost/oauth2-redirect.html' ], 'postLogoutRedirectUris': [ 'http://testhost/account/login' ], 'allowedCorsOrigins': [ 'http://testswaggerhost' ], 'AllowedGrantTypes': [ 'implicit' ], 'allowedScopes': [ 'openid', 'profile', 'testAPI' ] } ] }";

        public static string ExpectedResourcesJsonAfterMap = "[{\"ApiSecrets\":[],\"Scopes\":[{\"Name\":\"TestAPI\",\"DisplayName\":\"Test API\",\"Description\":null,\"Required\":false,\"Emphasize\":false,\"ShowInDiscoveryDocument\":true,\"UserClaims\":[]}],\"Enabled\":true,\"Name\":\"TestAPI\",\"DisplayName\":\"Test API\",\"Description\":null,\"UserClaims\":[],\"Properties\":{}}]";

        public static string ExpectedClientsJsonAfterMap = "[{\"Enabled\":true,\"ClientId\":\"Test_Client_1\",\"ProtocolType\":\"oidc\",\"ClientSecrets\":[],\"RequireClientSecret\":true,\"ClientName\":\"Test_Client\",\"Description\":null,\"ClientUri\":null,\"LogoUri\":null,\"RequireConsent\":false,\"AllowRememberConsent\":true,\"AllowedGrantTypes\":[\"implicit\"],\"RequirePkce\":false,\"AllowPlainTextPkce\":false,\"AllowAccessTokensViaBrowser\":true,\"RedirectUris\":[\"http://testhost1:\",\"http://testhost2\"],\"PostLogoutRedirectUris\":[\"http://testhost/account/login\"],\"FrontChannelLogoutUri\":null,\"FrontChannelLogoutSessionRequired\":true,\"BackChannelLogoutUri\":null,\"BackChannelLogoutSessionRequired\":true,\"AllowOfflineAccess\":false,\"AllowedScopes\":[\"openid\",\"profile\",\"testAPI\"],\"AlwaysIncludeUserClaimsInIdToken\":false,\"IdentityTokenLifetime\":300,\"AccessTokenLifetime\":3600,\"AuthorizationCodeLifetime\":300,\"AbsoluteRefreshTokenLifetime\":2592000,\"SlidingRefreshTokenLifetime\":1296000,\"ConsentLifetime\":null,\"RefreshTokenUsage\":1,\"UpdateAccessTokenClaimsOnRefresh\":false,\"RefreshTokenExpiration\":1,\"AccessTokenType\":0,\"EnableLocalLogin\":true,\"IdentityProviderRestrictions\":[],\"IncludeJwtId\":false,\"Claims\":[],\"AlwaysSendClientClaims\":false,\"ClientClaimsPrefix\":\"client_\",\"PairWiseSubjectSalt\":null,\"UserSsoLifetime\":null,\"UserCodeType\":null,\"DeviceCodeLifetime\":300,\"AllowedCorsOrigins\":[\"http://testhost\"],\"Properties\":{}},{\"Enabled\":true,\"ClientId\":\"Test_Client_2\",\"ProtocolType\":\"oidc\",\"ClientSecrets\":[],\"RequireClientSecret\":true,\"ClientName\":\"Test Client 2\",\"Description\":null,\"ClientUri\":null,\"LogoUri\":null,\"RequireConsent\":false,\"AllowRememberConsent\":true,\"AllowedGrantTypes\":[\"implicit\"],\"RequirePkce\":false,\"AllowPlainTextPkce\":false,\"AllowAccessTokensViaBrowser\":true,\"RedirectUris\":[\"http://testSwaggerhost/oauth2-redirect.html\"],\"PostLogoutRedirectUris\":[\"http://testhost/account/login\"],\"FrontChannelLogoutUri\":null,\"FrontChannelLogoutSessionRequired\":true,\"BackChannelLogoutUri\":null,\"BackChannelLogoutSessionRequired\":true,\"AllowOfflineAccess\":false,\"AllowedScopes\":[\"openid\",\"profile\",\"testAPI\"],\"AlwaysIncludeUserClaimsInIdToken\":false,\"IdentityTokenLifetime\":300,\"AccessTokenLifetime\":43200,\"AuthorizationCodeLifetime\":300,\"AbsoluteRefreshTokenLifetime\":2592000,\"SlidingRefreshTokenLifetime\":1296000,\"ConsentLifetime\":null,\"RefreshTokenUsage\":1,\"UpdateAccessTokenClaimsOnRefresh\":false,\"RefreshTokenExpiration\":1,\"AccessTokenType\":0,\"EnableLocalLogin\":true,\"IdentityProviderRestrictions\":[],\"IncludeJwtId\":false,\"Claims\":[],\"AlwaysSendClientClaims\":false,\"ClientClaimsPrefix\":\"client_\",\"PairWiseSubjectSalt\":null,\"UserSsoLifetime\":null,\"UserCodeType\":null,\"DeviceCodeLifetime\":300,\"AllowedCorsOrigins\":[\"http://testswaggerhost\"],\"Properties\":{}}]";
    }
}
