# Generated by Django 2.2.3 on 2019-07-15 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='intro_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_continue_button_text',
            field=models.CharField(default='Continue', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_header',
            field=models.CharField(default='welcome to our website!', max_length=50),
        ),
    ]
