# Generated by Django 2.2.3 on 2019-07-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190716_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='client_firstname',
            field=models.CharField(default='Paul', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_organisationName',
            field=models.CharField(default='Plinx', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_surname',
            field=models.CharField(default='Marrable', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_header',
            field=models.CharField(default='Plinx', max_length=50),
        ),
    ]
