# Generated by Django 2.2.3 on 2019-08-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190717_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='client_isOrganisation',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_firstname',
            field=models.CharField(default='Test Fname', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_organisationName',
            field=models.CharField(default='Test company 1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_surname',
            field=models.CharField(default='Test Surname', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_header',
            field=models.CharField(default='Test company 1', max_length=50),
        ),
    ]
