# Generated by Django 2.2.3 on 2019-08-13 22:19

import PlinxPlanner.businessLogic.httpManager
from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190728_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='intro_header',
            field=models.CharField(default=PlinxPlanner.businessLogic.httpManager.Content.get_intro_title, max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_text',
            field=wagtail.core.fields.RichTextField(blank=True, default=PlinxPlanner.businessLogic.httpManager.Content.get_intro_text),
        ),
    ]
