# Generated by Django 2.2.3 on 2019-09-16 21:18

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro_header', models.CharField(default='oi', max_length=50)),
                ('intro_text', wagtail.core.fields.RichTextField(blank=True)),
                ('intro_continue_button_text', models.CharField(default='Continue', max_length=50)),
                ('client_firstname', models.CharField(default='joij', max_length=50)),
                ('client_surname', models.CharField(default='oij', max_length=50)),
                ('client_organisationName', models.CharField(default='oi', max_length=50, null=True)),
                ('intro_background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
